export interface MerchantRequest {
  email: string;
  password?: string; // Optional if existing user update, required for new registration
  lastName: string;
  firstName: string;
  isActive?: boolean;
  phoneNumber: string;
  birthDate?: string; // LocalDateTime from backend -> string
  businessName: string;
  registrationNumber?: string; // Optional, might be generated by backend or not always required
  bankTrackingId?: string; // UUID from backend -> string
  accountNumber?: string;
}

export interface MerchantResponse {
  trackingId: string;
  email: string;
  lastName: string;
  firstName: string;
  isActive: boolean;
  phoneNumber: string;
  birthDate?: string; // LocalDateTime from backend -> string
  businessName: string;
}
